env:
  CODE_COVERAGE: '1'
  NODE_ENV: 'test'
steps:
  - command: .buildkite/scripts/lifecycle/pre_build.sh
    label: Pre-Build
    timeout_in_minutes: 10

  - wait

  - command: .buildkite/scripts/steps/build_kibana.sh
    label: Build Kibana Distribution and Plugins
    agents:
      queue: c2-16
    key: build
    if: "build.env('KIBANA_BUILD_ID') == null || build.env('KIBANA_BUILD_ID') == ''"
    timeout_in_minutes: 60

  - command: .buildkite/scripts/steps/code_coverage/xpack_cigroup.sh
    label: 'Default CI Group'
    parallelism: 13
    agents:
      queue: ci-group-6
    depends_on: build
    timeout_in_minutes: 250
    key: default-cigroup
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - command: .buildkite/scripts/steps/code_coverage/oss_cigroup.sh
    label: 'OSS CI Group'
    parallelism: 11
    agents:
      queue: ci-group-4d
    depends_on: build
    timeout_in_minutes: 120
    key: oss-cigroup
    retry:
      automatic:
        - exit_status: '*'
          limit: 1

  - command: .buildkite/scripts/steps/code_coverage/jest.sh
    label: 'Jest Tests'
    agents:
      queue: c2-16
    timeout_in_minutes: 150
    key: jest

  - wait: ~
    continue_on_failure: true

  - command: .buildkite/scripts/lifecycle/post_build.sh
    label: Post-Build
    timeout_in_minutes: 10
